name: "Tests"

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
#  main:
#    name: Run tests
#    runs-on: [self-hosted, Linux, X64]
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: '3.9.16'
#        cache: 'pip'
#    - run: pip install black flake8 isort
#    - run: make source_code_check_format
#    - run: pip install -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu117
#    - run: pytest --verbose
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      notebooks: ${{ steps.filter.outputs.changed_files }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - added|modified: '**.ipynb'
  notebooks:
    name: Run notebooks
    needs: changes
    strategy:
      matrix:
        notebook: ${{ fromJSON(needs.changes.outputs.notebooks) }}
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.16'
          cache: 'pip'
      - run: pip install jupyter nbconvert
      - run: jupyter nbconvert --execute --clear-output ${{ matrix.notebook }}