name: "Tests"

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
#  main:
#    name: Run tests
#    runs-on: [self-hosted, Linux, X64]
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: '3.9.16'
#        cache: 'pip'
#    - run: pip install black flake8 isort
#    - run: make source_code_check_format
#    - run: pip install -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu117
#    - run: pytest --verbose
  notebooks:
    name: Run notebooks
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.16'
          cache: 'pip'
      - run: pip install nbconvert
      - run: jupyter nbconvert --execute --clear-output experimental/whisper/speedup.ipynb